name: test
on: push
jobs:
  standard:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.1]
        rails: [7.0.3.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup git
        run: git config --global user.email "test@example.com" && git config --global user.name "Alice Tester"
      - name: Install rails
        run: gem install rails -v ${{ matrix.rails }}
      - run: ruby test/test_rails_new.rb
